name: CI

on: [ push, pull_request, workflow_dispatch ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        graalvm-version: [ 21 ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - uses: graalvm/setup-graalvm@v1
        with:
          distribution: 'graalvm-community'
          java-version: ${{ matrix.graalvm-version }}
          cache: 'maven'

      - name: GraalVM Compile
        run: ./mvnw clean -Pnative spring-boot:build-image -Dspring-boot.build-image.imagePlatform=linux/arm64
